application: mp3-online
version: 4
runtime: python
api_version: 1
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 )$


handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /img
  static_dir: img

- url: /jscripts
  static_dir: jscripts

- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /crossdomain.xml
  static_files: img/crossdomain.xml
  upload: img/crossdomain.xml

- url: /mtvustop100.html
  static_files: mp3/mtv_ustop10.html
  upload: mp3/mtv_ustop10.html

- url: /billboard_country30.html
  static_files: mp3/billboard_country30.html
  upload: mp3/billboard_country30.html

- url: /billboard_hiphop50.html
  static_files: mp3/billboard_hiphop50.html
  upload: mp3/billboard_hiphop50.html

- url: /billboard_hot100.html
  static_files: mp3/billboard_hot100.html
  upload: mp3/billboard_hot100.html

- url: /billboard_jazz10.html
  static_files: mp3/billboard_jazz10.html
  upload: mp3/billboard_jazz10.html

- url: /billboard_latin20.html
  static_files: mp3/billboard_latin20.html
  upload: mp3/billboard_latin20.html

- url: /billboard_pop20.html
  static_files: mp3/billboard_pop20.html
  upload: mp3/billboard_pop20.html

- url: /billboard_radio40.html
  static_files: mp3/billboard_radio40.html
  upload: mp3/billboard_radio40.html

- url: /billboard_rock30.html
  static_files: mp3/billboard_rock30.html
  upload: mp3/billboard_rock30.html

- url: /eula.txt
  static_files: mp3/eula.txt
  upload: mp3/eula.txt

- url: /static
  static_dir: static

- url: /canvas.html
  static_files: jscripts/friendconnect/canvas.html
  upload: jscripts/friendconnect/canvas.html

- url: /rpc_relay.html
  static_files: jscripts/friendconnect/rpc_relay.html
  upload: jscripts/friendconnect/rpc_relay.html  

- url: /appadmin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /.*
  script: main.py

